### ISSUE TITLE
busybox pod terminates after 42 seconds?

### ISSUE THREAD

**Issue by mlsorensen** [fabiand/kubectl-plugin-pvc#1]
https://github.com/fabiand/kubectl-plugin-pvc/blob/2f2e562976fcd81f426d80eff2c2524d073854cf/pvc#L73

Is there a reason this sleep is "42"? Can it be increased to accommodate larger copies? From my understanding the pod will be shut down when the copy is done, regardless.

**Comment by fabiand** [comment]
I thought that sleep is just needed to spawn the pod - and that it would then wait until cp finishes.

To make it more safe we can actually do a simple fix which sleeps, waits for cp, and then waits for cp to end.

**Comment by fabiand** [comment]
This is a simple fix, can be solved more elegantly.
